---
# Copyright (C) 2021-2022 Robert Wimmer
# SPDX-License-Identifier: GPL-3.0-or-later

- hosts: all
  remote_user: vagrant
  become: true
  gather_facts: true
  tasks:
    - block:
      - name: (Archlinux) Init pacman
        raw: |
          pacman-key --init
          pacman-key --populate archlinux
        changed_when: false
        ignore_errors: true

      - name: (Archlinux) Update pacman cache
        community.general.pacman:
          update_cache: yes
        changed_when: false
      when: ansible_distribution|lower == 'archlinux'

    - name: (Ubuntu) Update APT package cache
      apt:
        update_cache: "true"
        cache_valid_time: 3600
      when: ansible_distribution|lower == 'ubuntu'

- hosts: test-lvm-ubuntu2004
  vars_files:
    - vars/test-lvm-ubuntu2004_create.yml 
  remote_user: vagrant
  become: true
  gather_facts: true
  tasks:
    - name: Include LVM role
      include_role:
        name: githubixx.lvm

- hosts: test-lvm-ubuntu1804
  remote_user: vagrant
  become: true
  gather_facts: true
  tasks:
    - name: Include LVM role
      include_role:
        name: githubixx.lvm

- hosts: test-lvm-debian10
  remote_user: vagrant
  become: true
  gather_facts: true
  tasks:
    - name: Include LVM role
      include_role:
        name: githubixx.lvm

- hosts: test-lvm-fedora33
  remote_user: vagrant
  become: true
  gather_facts: true
  tasks:
    - name: Include LVM role
      include_role:
        name: githubixx.lvm

- hosts: test-lvm-fedora34
  remote_user: vagrant
  become: true
  gather_facts: true
  tasks:
    - name: Include LVM role
      include_role:
        name: githubixx.lvm

- hosts: test-lvm-centos8
  remote_user: vagrant
  become: true
  gather_facts: true
  tasks:
    - name: Include LVM role
      include_role:
        name: githubixx.lvm

- hosts: test-lvm-centos7
  remote_user: vagrant
  become: true
  gather_facts: true
  tasks:
    - name: Include LVM role
      include_role:
        name: githubixx.lvm

- hosts: test-lvm-arch
  vars_files:
    - vars/test-lvm-arch_create.yml
  remote_user: vagrant
  become: true
  gather_facts: true
  tasks:
    - name: Include LVM role
      include_role:
        name: githubixx.lvm

- hosts: test-lvm-arch
  vars_files:
    - vars/test-lvm-arch_delete.yml
  remote_user: vagrant
  become: true
  gather_facts: true
  tasks:
    - name: Include LVM role
      include_role:
        name: githubixx.lvm

- hosts: test-lvm-opensuse-leap
  remote_user: vagrant
  become: true
  gather_facts: true
  tasks:
    - name: Include LVM role
      include_role:
        name: githubixx.lvm

- hosts: test-lvm-debian11
  remote_user: vagrant
  become: true
  gather_facts: true
  tasks:
    - name: Include LVM role
      include_role:
        name: githubixx.lvm
