---
# Copyright (C) 2021-2024 Robert Wimmer
# SPDX-License-Identifier: GPL-3.0-or-later

- hosts: test-lvm-ubuntu2204
  vars_files:
    - vars/test-lvm-minimal.yml
  remote_user: vagrant
  become: true
  gather_facts: true
  tasks:
    - name: Include LVM role
      include_role:
        name: githubixx.lvm

- hosts: test-lvm-ubuntu2004
  vars_files:
    - vars/test-lvm-ubuntu2004_create.yml
  remote_user: vagrant
  become: true
  gather_facts: true
  tasks:
    - name: Include LVM role
      include_role:
        name: githubixx.lvm

- hosts: test-lvm-ubuntu1804
  vars_files:
    - vars/test-lvm-minimal.yml
  remote_user: vagrant
  become: true
  gather_facts: true
  tasks:
    - name: Include LVM role
      include_role:
        name: githubixx.lvm

- hosts: test-lvm-debian10
  vars_files:
    - vars/test-lvm-minimal.yml
  remote_user: vagrant
  become: true
  gather_facts: true
  tasks:
    - name: Include LVM role
      include_role:
        name: githubixx.lvm

- hosts: test-lvm-fedora35
  vars_files:
    - vars/test-lvm-minimal.yml
  remote_user: vagrant
  become: true
  gather_facts: true
  tasks:
    - name: Include LVM role
      include_role:
        name: githubixx.lvm

- hosts: test-lvm-fedora36
  vars_files:
    - vars/test-lvm-minimal.yml
  remote_user: vagrant
  become: true
  gather_facts: true
  tasks:
    - name: Include LVM role
      include_role:
        name: githubixx.lvm

- hosts: test-lvm-centos7
  vars_files:
    - vars/test-lvm-minimal.yml
  remote_user: vagrant
  become: true
  gather_facts: true
  tasks:
    - name: Include LVM role
      include_role:
        name: githubixx.lvm

- hosts: test-lvm-arch
  vars_files:
    - vars/test-lvm-arch_create.yml
  remote_user: vagrant
  become: true
  gather_facts: true
  tasks:
    - name: Include LVM role
      include_role:
        name: githubixx.lvm

- hosts: test-lvm-arch
  vars_files:
    - vars/test-lvm-arch_delete.yml
  remote_user: vagrant
  become: true
  gather_facts: true
  tasks:
    - name: Include LVM role
      include_role:
        name: githubixx.lvm

- hosts: test-lvm-opensuse-leap-15-3
  vars_files:
    - vars/test-lvm-minimal.yml
  remote_user: vagrant
  become: true
  gather_facts: true
  tasks:
    - name: Include LVM role
      include_role:
        name: githubixx.lvm

- hosts: test-lvm-opensuse-leap-15-4
  vars_files:
    - vars/test-lvm-minimal.yml
  remote_user: vagrant
  become: true
  gather_facts: true
  tasks:
    - name: Include LVM role
      include_role:
        name: githubixx.lvm

- hosts: test-lvm-debian11
  vars_files:
    - vars/test-lvm-minimal.yml
  remote_user: vagrant
  become: true
  gather_facts: true
  tasks:
    - name: Include LVM role
      include_role:
        name: githubixx.lvm
