---
# Copyright (C) 2021-2022 Robert Wimmer
# SPDX-License-Identifier: GPL-3.0-or-later

dependency:
  name: galaxy

driver:
  name: vagrant
  provider:
    name: libvirt
    type: libvirt

platforms:
  - name: test-lvm-ubuntu2204
    box: generic/ubuntu2204
    memory: 1024
    cpus: 2
    provider_raw_config_args:
      - "storage :file, :type => 'qcow2', :device => 'vdb', :size => '1G'"
    interfaces:
      - auto_config: true
        network_name: private_network
        type: static
        ip: 192.168.10.10
  - name: test-lvm-ubuntu2004
    box: generic/ubuntu2004
    memory: 1024
    cpus: 2
    provider_raw_config_args:
      - "storage :file, :type => 'qcow2', :device => 'vdb', :size => '1G'"
    interfaces:
      - auto_config: true
        network_name: private_network
        type: static
        ip: 192.168.10.20
  - name: test-lvm-fedora39
    box: generic/fedora39
    memory: 1024
    cpus: 2
    provider_raw_config_args:
      - "storage :file, :type => 'qcow2', :device => 'vdb', :size => '1G'"
    interfaces:
      - auto_config: true
        network_name: private_network
        type: static
        ip: 192.168.10.60
  - name: test-lvm-centos7
    box: generic/centos7
    memory: 1024
    cpus: 2
    provider_raw_config_args:
      - "storage :file, :type => 'qcow2', :device => 'vdb', :size => '1G'"
    interfaces:
      - auto_config: true
        network_name: private_network
        type: static
        ip: 192.168.10.70
  - name: test-lvm-arch
    box: archlinux/archlinux
    memory: 1024
    cpus: 2
    provider_raw_config_args:
      - "storage :file, :type => 'qcow2', :device => 'vdb', :size => '1G'"
      - "storage :file, :type => 'qcow2', :device => 'vdc', :size => '1G'"
    interfaces:
      - auto_config: true
        network_name: private_network
        type: static
        ip: 192.168.10.80
  - name: test-lvm-opensuse-leap-15-3
    box: opensuse/Leap-15.3.x86_64
    memory: 1024
    cpus: 2
    provider_raw_config_args:
      - "storage :file, :type => 'qcow2', :device => 'vdb', :size => '1G'"
    interfaces:
      - auto_config: true
        network_name: private_network
        type: static
        ip: 192.168.10.90
  - name: test-lvm-opensuse-leap-15-4
    box: opensuse/Leap-15.4.x86_64
    memory: 1024
    cpus: 2
    provider_raw_config_args:
      - "storage :file, :type => 'qcow2', :device => 'vdb', :size => '1G'"
    interfaces:
      - auto_config: true
        network_name: private_network
        type: static
        ip: 192.168.10.100
  - name: test-lvm-debian11
    box: generic/debian11
    memory: 1024
    cpus: 2
    provider_raw_config_args:
      - "storage :file, :type => 'qcow2', :device => 'vdb', :size => '1G'"
    interfaces:
      - auto_config: true
        network_name: private_network
        type: static
        ip: 192.168.10.110

provisioner:
  name: ansible
  connection_options:
    ansible_ssh_user: vagrant
    ansible_become: true
  log: true
  lint: yamllint . && flake8 && ansible-lint

scenario:
  name: kvm
  test_sequence:
    - prepare
    - converge

verifier:
  name: ansible
  enabled: false
